2023-05-08 22:47:53,383 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.67.203.10:36781'
2023-05-08 22:47:59,778 - distributed.worker - INFO -       Start worker at:   tcp://10.67.203.10:33274
2023-05-08 22:47:59,779 - distributed.worker - INFO -          Listening to:   tcp://10.67.203.10:33274
2023-05-08 22:47:59,779 - distributed.worker - INFO -           Worker name:           SLURMCluster-353
2023-05-08 22:47:59,779 - distributed.worker - INFO -          dashboard at:         10.67.203.10:40661
2023-05-08 22:47:59,779 - distributed.worker - INFO - Waiting to connect to:    tcp://10.70.211.9:42768
2023-05-08 22:47:59,779 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:59,779 - distributed.worker - INFO -               Threads:                          1
2023-05-08 22:47:59,779 - distributed.worker - INFO -                Memory:                  17.70 GiB
2023-05-08 22:47:59,779 - distributed.worker - INFO -       Local Directory: /opt/tmp/tmp/dask-worker-space/worker-a8sl5zv_
2023-05-08 22:47:59,779 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:48:03,076 - distributed.worker - INFO -         Registered to:    tcp://10.70.211.9:42768
2023-05-08 22:48:03,076 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:48:03,077 - distributed.core - INFO - Starting established connection to tcp://10.70.211.9:42768
Matplotlib created a temporary config/cache directory at /opt/tmp/tmp/matplotlib-ptjqtqp4 because the default path (/home/vlecoz/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-05-08 22:48:12,968 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.61s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
  0%|          | 0/9 [00:00<?, ?it/s] 22%|██▏       | 2/9 [00:00<00:00, 12.30it/s] 44%|████▍     | 4/9 [00:00<00:00, 12.50it/s] 67%|██████▋   | 6/9 [00:00<00:00, 12.58it/s] 89%|████████▉ | 8/9 [00:00<00:00, 12.69it/s]100%|██████████| 9/9 [00:00<00:00, 12.60it/s]
  0%|          | 0/50 [00:00<?, ?it/s]100%|██████████| 50/50 [00:00<00:00, 907858.01it/s]
0it [00:00, ?it/s]2it [00:00, 1486.81it/s]
  0%|          | 0/9 [00:00<?, ?it/s]100%|██████████| 9/9 [00:00<00:00, 1401.06it/s]
  0%|          | 0/8 [00:00<?, ?it/s]/mnt/live/user/vlecoz/Secured_interbank_network/emp_metrics.py:28: RuntimeWarning: invalid value encountered in long_scalars
  np.logical_and(
100%|██████████| 8/8 [00:00<00:00, 10195.82it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 4078.57it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 3096.28it/s]
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [00:00<?, ?it/s]
2023-05-08 22:48:16,546 - distributed.worker - WARNING - Compute Failed
Key:       single_run-27ac91c3-8e8f-4fee-83a7-cb20fee105b4
Function:  execute_task
args:      ((<function apply at 0x7f32b62b8040>, <function single_run at 0x7f32981f55e0>, [], (<class 'dict'>, [['nb_banks', 50], ['alpha_init', 0.29], ['alpha', 0.01], ['beta_init', 0.5], ['beta_reg', 0.5], ['beta_star', 0.5], ['gamma', 0.03], ['collateral_value', 1.0], ['initialization_method', 'pareto'], ['alpha_pareto', 1.3], ['shocks_method', 'non-conservative'], ['shocks_law', 'normal-mean-reverting'], ['shocks_vol', 0.05], ['result_location', './results/multiple_run/alpha_init/0.29/'], ['min_repo_trans_size', 1e-08], ['nb_steps', 10], ['dump_period', 10], ['plot_period', 10], ['cp_option', False], ['LCR_mgt_opt', False]])))
kwargs:    {}
Exception: "ValueError('zero-size array to reduction operation minimum which has no identity')"

slurmstepd: error: *** JOB 16609070 ON srv007071 CANCELLED AT 2023-05-08T22:48:17 ***
